### PR TITLE
Create the generator

### LINKED ISSUE #2: Create the generator
This generator should handle setting up an application that is already set up with `donejs-heroku` to use CD with travis.

This should add the following configuration to the `.travis.yml` file, being careful not to override any user configuration.

```
deploy:
  skip_cleanup: true
  provider: "heroku"
  app: <my-app>
```

Not sure how to get the `<my-app>`, possibly by calling the heroku cli, or possibly we should save this info some where.

### PR DESCRIPTION
**Pull request by m-mujica**
Closes #2 

This generators runs a series of checks with early returns:

a) if there is no `.travis.yml` it fails with:
    `Travis config file not found!. Please run "donejs add travis" first`

b) if `.travis.yml` has deploy settings already, it fails with:
     `There are deploy settings in your .travis.yml already. Please delete the "deploy" section before running this command` 
     (@matthewp I'm not sure about this message, ideas?)

c) if there is no Procfile, it fails with:
    `Heroku Procfile not found!. Please run "donejs add heroku" first.`

if all checks pass, then it prompts the user to type the heroku app name, it runs

`heroku apps --json`

sorts the result by `created_at` date and returns the most recent name (which for guide users should be THE name) and uses it as the default for the prompt. 

`? What is the name of the Heroku application? (secret-thicket-26115)`

Thoughts?

PS: Another detail, the YAML parser I'm using strips unnecessary `"` from the yaml, that introduces some noise in the `.travis.yml` diff `donejs add heroku-to-travis` generates.... Wondering if we should strip those in advance from `donejs-travis` so the diff only includes the `deploy` section.

### CODE REVIEW

**Comment by m-mujica** [comment]
Another thought about `donejs-heroku`

We could prompt the user to type the heroku app name they want, and store that http://yeoman.io/authoring/storage.html

We might ask them first if they want to use a random name, or type their own maybe... And this package would try to read the name from the config file first, then do the `heroku apps --json` as the fallback.

**Comment by matthewp** [comment]
Sounds good! I like the touch of getting the app names for the prompt.  I agree about fixing the Yaml as part of donejs-travis.

**Comment by m-mujica** [comment]
This now tries to read the name from the top level config and use it as a suggestion for the user, it fallback to executing `heroku apps --json` and grabbing the most recent app.

Also, look at that diff <3

screen shot 2018-02-13 at 12 40 37 pm

**NOTE**

Reaching for the global config felt weird, I actually isolated the code. It seems the yeoman way in this case would have a single generator and make `add travis`, `add heroku`, `add heroku-to-travis` (would be sub-generators) share a single config object. That way we'd just do:

`this.config.get('herokuAppName')` in a sub-task.

Not sure if we want to do this tho.

**Comment by matthewp** [comment]
Diff looks great, lgtm.

**Pull request merged**
